sudo apt install php8.1 -y
sudo apt install php8.1-bcmath -y
sudo apt install php8.1-bz2 -y
sudo apt install php8.1-cli -y
sudo apt install php8.1-common -y
sudo apt install php8.1-curl -y
sudo apt install php8.1-dev -y
sudo apt install php8.1-gd -y
sudo apt install php8.1-igbinary -y
sudo apt install php8.1-imagick -y
sudo apt install php8.1-imap -y
sudo apt install php8.1-intl -y
sudo apt install php8.1-mbstring -y
sudo apt install php8.1-memcached -y
sudo apt install php8.1-msgpack -y
sudo apt install php8.1-mysql -y
sudo apt install php8.1-opcache -y
sudo apt install php8.1-pgsql -y
sudo apt install php8.1-readline -y
sudo apt install php8.1-redis -y
sudo apt install php8.1-ssh2 -y
sudo apt install php8.1-tidy -y
sudo apt install php8.1-xml -y
sudo apt install php8.1-xmlrpc -y
sudo apt install php8.1-zip -y
